---
function:
  name: omni-wt-rt-edi-204-header-${self:provider.stage}
  handler: src/realtime/edi204Header.handler
  memorySize: 1024
  timeout: 300
  runtime: nodejs18.x
  
  layers:
    - { Ref: OmniRealTimeReplicationLayerLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/realtime/edi204Header.js"
      - "src/shared/**"
  environment:
    DYNAMO_DB_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/edi-204-header/ddb.tableName~true}
    SNS_TOPIC_ARN: ${ssm:/omni-reports/${self:provider.stage}/error-notification/sns/arn}
  events:
    - sqs:
        arn: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/edi-204-header/queue.arn~true}
        batchSize: 10
        functionResponseType: ReportBatchItemFailures
  iamRoleStatementsName: omni-wt-rt-edi-204-header-${self:provider.stage}-role
  iamRoleStatements:
    -
      Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "*"