---
function:
  name: omni-wt-rt-instructions-${self:provider.stage}
  handler: src/realtime/instructionsRt.handler
  memorySize: 1024
  timeout: 300
  runtime: nodejs18.x
  
  tags:
    Name: omni-wt-rt-instructions-${self:provider.stage}
  layers:
    - { Ref: OmniRealTimeReplicationLayerLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/realtime/instructionsRt.js"
      - "src/shared/**"
  environment:
    DYNAMO_DB_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/instructions/ddb.tableName~true}
  events:
    - sqs:
        arn: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/instructions/queue.arn~true}
        batchSize: 10
        functionResponseType: ReportBatchItemFailures
  iamRoleStatementsName: omni-wt-rt-instructions-${self:provider.stage}-role
  iamRoleStatements:
    -
      Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "*"