---
function:
  name: omni-wt-rt-shipment-ocean-import-${self:provider.stage}
  handler: src/realtime/shipmentOceanImportRt.handler
  memorySize: 1024
  timeout: 300
  runtime: nodejs18.x
  tags:
    Name: omni-wt-rt-shipment-ocean-import-${self:provider.stage}
  layers:
    - { Ref: OmniRealTimeReplicationLayerLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/realtime/shipmentOceanImportRt.js"
      - "src/shared/**"
  environment:
    DYNAMO_DB_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-ocean-import/ddb.tableName~true}
  events:
    - sqs:
        arn: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-ocean-import/queue.arn~true}
        batchSize: 10
        functionResponseType: ReportBatchItemFailures
  iamRoleStatementsName: omni-wt-rt-shipment-ocean-import-${self:provider.stage}-role
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "*"
