---
function:
  name: omni-wt-consignee-source-ddb-to-sns-${self:provider.stage}
  handler: src/dynamoStreamToSns/consigneeStreamToSns.handler
  # provisionedConcurrency: 1
  # concurrencyAutoscaling: true
  layers:
    - { Ref: OmniRealTimeReplicationLayerLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/dynamoStreamToSns/consigneeStreamToSns.js"
      - "src/shared/**"
  events:
    - stream: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/consignee/ddb.streamArn~true}
  environment:
    # SNS_TOPIC_ARN: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/consignee/sns.arn~true}
    SNS_TOPIC_ARN: arn:aws:sns:us-east-1:332281781429:omni-wt-rt-consignee-dev
